package com.github.lynchmaniac.poilight.enumeration;



/**
 * Enumeration for different predefined excel styles.
 * To understand all the styles, please see at 
 * examples/Predefines Excel Style.xlsx
 * 
 * @author vpiard
 * @since 0.1
 */
public enum BoardStyles {
	/**
	 * The Default style
	 */
	BOARD_DEFAULT_STYLE, 
	BOARD_LIGHT_GRAY_1_STYLE,
	BOARD_LIGHT_GRAY_2_STYLE,
	BOARD_LIGHT_GRAY_3_STYLE,

	BOARD_LIGHT_BLUE_1_STYLE,
	BOARD_LIGHT_BLUE_2_STYLE,
	BOARD_LIGHT_BLUE_3_STYLE,

	BOARD_LIGHT_RED_1_STYLE,
	BOARD_LIGHT_RED_2_STYLE,
	BOARD_LIGHT_RED_3_STYLE,

	BOARD_LIGHT_GREEN_1_STYLE,
	BOARD_LIGHT_GREEN_2_STYLE,
	BOARD_LIGHT_GREEN_3_STYLE,

	BOARD_LIGHT_PURPLE_1_STYLE,
	BOARD_LIGHT_PURPLE_2_STYLE,
	BOARD_LIGHT_PURPLE_3_STYLE,

	BOARD_LIGHT_TURQUOISE_1_STYLE,
	BOARD_LIGHT_TURQUOISE_2_STYLE,
	BOARD_LIGHT_TURQUOISE_3_STYLE,

	BOARD_LIGHT_ORANGE_1_STYLE,
	BOARD_LIGHT_ORANGE_2_STYLE,
	BOARD_LIGHT_ORANGE_3_STYLE,
	
	BOARD_MEDIUM_GRAY_1_STYLE,
	BOARD_MEDIUM_GRAY_2_STYLE,
	BOARD_MEDIUM_GRAY_3_STYLE,
	BOARD_MEDIUM_GRAY_4_STYLE,

	BOARD_MEDIUM_BLUE_1_STYLE,
	BOARD_MEDIUM_BLUE_2_STYLE,
	BOARD_MEDIUM_BLUE_3_STYLE,
	BOARD_MEDIUM_BLUE_4_STYLE,

	BOARD_MEDIUM_RED_1_STYLE,
	BOARD_MEDIUM_RED_2_STYLE,
	BOARD_MEDIUM_RED_3_STYLE,
	BOARD_MEDIUM_RED_4_STYLE,

	BOARD_MEDIUM_GREEN_1_STYLE,
	BOARD_MEDIUM_GREEN_2_STYLE,
	BOARD_MEDIUM_GREEN_3_STYLE,
	BOARD_MEDIUM_GREEN_4_STYLE,

	BOARD_MEDIUM_PURPLE_1_STYLE,
	BOARD_MEDIUM_PURPLE_2_STYLE,
	BOARD_MEDIUM_PURPLE_3_STYLE,
	BOARD_MEDIUM_PURPLE_4_STYLE,

	BOARD_MEDIUM_TURQUOISE_1_STYLE,
	BOARD_MEDIUM_TURQUOISE_2_STYLE,
	BOARD_MEDIUM_TURQUOISE_3_STYLE,
	BOARD_MEDIUM_TURQUOISE_4_STYLE,

	BOARD_MEDIUM_ORANGE_1_STYLE,
	BOARD_MEDIUM_ORANGE_2_STYLE,
	BOARD_MEDIUM_ORANGE_3_STYLE,
	BOARD_MEDIUM_ORANGE_4_STYLE,
	
	BOARD_DARK_GRAY_1_STYLE,
	BOARD_DARK_BLUE_1_STYLE,
	BOARD_DARK_RED_1_STYLE,
	BOARD_DARK_GREEN_1_STYLE,
	BOARD_DARK_PURPLE_1_STYLE,
	BOARD_DARK_TURQUOISE_1_STYLE,
	BOARD_DARK_ORANGE_1_STYLE,
	
	BOARD_DARK_MIX_1_STYLE,
	BOARD_DARK_MIX_2_STYLE,
	BOARD_DARK_MIX_3_STYLE,
	BOARD_DARK_MIX_4_STYLE;
}
